# Generated by Django 5.1.6 on 2025-03-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sobre_mi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
