# Generated by Django 5.1.6 on 2025-03-23 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('markt', '0009_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguidor_object_id', models.PositiveIntegerField()),
                ('seguido_object_id', models.PositiveIntegerField()),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True)),
                ('seguidor_content_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='seguimientos_realizados',
                    to='contenttypes.contenttype'
                )),
                ('seguido_content_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='seguidores',
                    to='contenttypes.contenttype'
                )),
            ],
            options={
                'unique_together': {('seguidor_content_type', 'seguidor_object_id', 'seguido_content_type', 'seguido_object_id')},
            },
        ),
    ]
