# Generated by Django 5.1.6 on 2025-03-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('markt', '0010_alter_seguimiento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seguido_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seguido_object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seguidor_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_realizados', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seguidor_object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
