# Generated by Django 5.1.6 on 2025-03-28 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0012_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_adjuntos/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('transferencia', 'Transferencia'), ('credito', 'Crédito 30-60-90 días'), ('webpay', 'Webpay'), ('cripto', 'Criptomonedas u otras')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto / Online'), ('terreno', 'En terreno / Despacho incluido')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tiempo_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('contacto_nombre', models.CharField(max_length=255)),
                ('contacto_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto_email', models.EmailField(max_length=254)),
                ('contacto_telefono', models.CharField(max_length=20)),
                ('contacto_web', models.URLField(blank=True, null=True)),
                ('archivos', models.ManyToManyField(blank=True, related_name='servicios', to='markt.archivoadjunto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='markt.empresa')),
                ('formas_pago', models.ManyToManyField(related_name='servicios', to='markt.formapago')),
                ('modalidades_atencion', models.ManyToManyField(related_name='servicios', to='markt.modalidadatencion')),
                ('regiones', models.ManyToManyField(related_name='servicios', to='markt.region')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_breve', models.TextField()),
                ('unidad_venta', models.CharField(max_length=100)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidad_geografica', models.ManyToManyField(related_name='productos', to='markt.region')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='markt.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='archivoadjunto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='markt.servicio'),
        ),
    ]
