# Generated by Django 5.1.6 on 2025-03-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0013_archivoadjunto_formapago_modalidadatencion_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidadatencion',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null='nullo'),
            preserve_default='nullo',
        ),
    ]
