# Generated by Django 5.1.6 on 2025-03-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0015_formapago_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
    ]
