# Generated by Django 5.1.6 on 2025-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0016_userprofile_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
    ]
