# Generated by Django 5.1.6 on 2025-04-21 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0018_conexion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='markt.servicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_servicio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
