# Generated by Django 5.1.6 on 2025-04-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0019_contactoservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('url_original', models.URLField(blank=True, max_length=500, null=True)),
                ('medio', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('informe_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
