# Generated by Django 5.1.6 on 2025-04-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0020_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
