# Generated by Django 5.1.6 on 2025-04-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0021_empresa_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='es_publico',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='abierta', max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitaciones_creadas', to='markt.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True)),
                ('empresa_ofertante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_realizadas', to='markt.empresa')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='markt.licitacion')),
                ('servicio_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='markt.servicio')),
            ],
            options={
                'unique_together': {('licitacion', 'empresa_ofertante', 'servicio_ofertado')},
            },
        ),
    ]
