# Generated by Django 5.1.6 on 2025-05-05 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0022_servicio_es_publico_licitacion_ofertalicitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_licitacion/')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_licitacion', to='markt.licitacion')),
            ],
        ),
    ]
