# Generated by Django 5.1.6 on 2025-05-26 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0024_cargoempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fuente', models.CharField(blank=True, max_length=255, null=True)),
                ('rubro', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='repositorio_recursos/')),
                ('fecha_subida', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
