# Generated by Django 5.1.6 on 2025-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0025_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comuna',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_fisica',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_empresa',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='empresa',
            name='giro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pagina_web',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='region',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono_empresa',
            field=models.IntegerField(default=0),
        ),
    ]
