# Generated by Django 5.1.6 on 2025-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0026_empresa_comuna_empresa_direccion_fisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono_empresa',
            field=models.IntegerField(default=1),
        ),
    ]
