# Generated by Django 5.1.6 on 2025-05-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0027_alter_empresa_telefono_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono_empresa',
            field=models.IntegerField(default=1, max_length=9),
        ),
    ]
