# Generated by Django 5.1.6 on 2025-06-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0028_alter_empresa_telefono_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_recursos/'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='palabrasClaves',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono_empresa',
            field=models.IntegerField(default=1),
        ),
    ]
