# Generated by Django 5.1.6 on 2025-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0029_recurso_imagen_recurso_palabrasclaves_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="correo_representante_legal",
            field=models.EmailField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos_empresas/"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="nombre_representante_legal",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="empresa",
            name="telefono_representante_legal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
