# Generated by Django 5.1.6 on 2025-06-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0030_empresa_correo_representante_legal_empresa_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="fecha_creacion_empresa",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
