# Generated by Django 5.1.6 on 2025-06-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0031_empresa_fecha_creacion_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="comuna",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="correo_representante_legal",
            field=models.EmailField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="giro",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre_empresa",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre_fantasia",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre_representante_legal",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="pagina_web",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="pais",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="razon_social",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="region",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="rubro",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="sector",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
