# Generated by Django 5.1.6 on 2025-06-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0033_alter_empresa_telefono_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="email_empresa",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
