# Generated by Django 5.1.6 on 2025-06-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0034_alter_empresa_email_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="comuna",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="correo_representante_legal",
            field=models.EmailField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="direccion_fisica",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="email_empresa",
            field=models.EmailField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="giro",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre_representante_legal",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="pagina_web",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="pais",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="region",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="rubro",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="sector",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
    ]
