# Generated by Django 5.1.6 on 2025-06-30 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0035_alter_empresa_comuna_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
