# Generated by Django 5.1.6 on 2025-06-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0036_alter_empresa_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="rut",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
