# Generated by Django 5.1.6 on 2025-06-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0037_alter_empresa_rut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="telefono_empresa",
            field=models.BigIntegerField(default=1, null=True),
        ),
    ]
