# Generated by Django 5.1.6 on 2025-06-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markt", "0038_alter_empresa_telefono_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="nombre_empresa",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre_fantasia",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="razon_social",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
    ]
