# Generated by Django 5.1.6 on 2025-07-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("markt", "0039_alter_empresa_nombre_empresa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecursoUsuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("fuente", models.CharField(blank=True, max_length=255, null=True)),
                ("rubro", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("archivo", models.FileField(upload_to="recursos/")),
                ("fecha_subida", models.DateTimeField()),
                ("palabrasClaves", models.TextField(default="")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="recursos_imagenes/"
                    ),
                ),
                ("author_id", models.PositiveIntegerField()),
                (
                    "author_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
