# Generated by Django 5.1.6 on 2025-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt', '0040_recursousuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursousuarios',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
    ]
